//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EmexApp.EmExDictionaries {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EmExDictionariesSoap", Namespace="http://tempuri.org/")]
    public partial class EmExDictionaries : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMakesDictOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConsumersDictOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPricesAndSignsDict2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPricesAndSignsDictOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConsumersDict_TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestConnectOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EmExDictionaries() {
            this.Url = global::EmexApp.Properties.Settings.Default.EmexApp_EmExDictionaries_EmExDictionaries;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMakesDictCompletedEventHandler GetMakesDictCompleted;
        
        /// <remarks/>
        public event GetConsumersDictCompletedEventHandler GetConsumersDictCompleted;
        
        /// <remarks/>
        public event GetPricesAndSignsDict2CompletedEventHandler GetPricesAndSignsDict2Completed;
        
        /// <remarks/>
        public event GetPricesAndSignsDictCompletedEventHandler GetPricesAndSignsDictCompleted;
        
        /// <remarks/>
        public event GetConsumersDict_TestCompletedEventHandler GetConsumersDict_TestCompleted;
        
        /// <remarks/>
        public event TestConnectCompletedEventHandler TestConnectCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMakesDict", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ShortMakeInfo[] GetMakesDict(long login, string password) {
            object[] results = this.Invoke("GetMakesDict", new object[] {
                        login,
                        password});
            return ((ShortMakeInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMakesDictAsync(long login, string password) {
            this.GetMakesDictAsync(login, password, null);
        }
        
        /// <remarks/>
        public void GetMakesDictAsync(long login, string password, object userState) {
            if ((this.GetMakesDictOperationCompleted == null)) {
                this.GetMakesDictOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMakesDictOperationCompleted);
            }
            this.InvokeAsync("GetMakesDict", new object[] {
                        login,
                        password}, this.GetMakesDictOperationCompleted, userState);
        }
        
        private void OnGetMakesDictOperationCompleted(object arg) {
            if ((this.GetMakesDictCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMakesDictCompleted(this, new GetMakesDictCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetConsumersDict", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsumerInfo[] GetConsumersDict(long login, string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> consumerId) {
            object[] results = this.Invoke("GetConsumersDict", new object[] {
                        login,
                        password,
                        consumerId});
            return ((ConsumerInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetConsumersDictAsync(long login, string password, System.Nullable<long> consumerId) {
            this.GetConsumersDictAsync(login, password, consumerId, null);
        }
        
        /// <remarks/>
        public void GetConsumersDictAsync(long login, string password, System.Nullable<long> consumerId, object userState) {
            if ((this.GetConsumersDictOperationCompleted == null)) {
                this.GetConsumersDictOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConsumersDictOperationCompleted);
            }
            this.InvokeAsync("GetConsumersDict", new object[] {
                        login,
                        password,
                        consumerId}, this.GetConsumersDictOperationCompleted, userState);
        }
        
        private void OnGetConsumersDictOperationCompleted(object arg) {
            if ((this.GetConsumersDictCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConsumersDictCompleted(this, new GetConsumersDictCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPricesAndSignsDict2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PriceAndSigns2[] GetPricesAndSignsDict2(long login, string password, string priceLogo, string destinationLogo) {
            object[] results = this.Invoke("GetPricesAndSignsDict2", new object[] {
                        login,
                        password,
                        priceLogo,
                        destinationLogo});
            return ((PriceAndSigns2[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPricesAndSignsDict2Async(long login, string password, string priceLogo, string destinationLogo) {
            this.GetPricesAndSignsDict2Async(login, password, priceLogo, destinationLogo, null);
        }
        
        /// <remarks/>
        public void GetPricesAndSignsDict2Async(long login, string password, string priceLogo, string destinationLogo, object userState) {
            if ((this.GetPricesAndSignsDict2OperationCompleted == null)) {
                this.GetPricesAndSignsDict2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPricesAndSignsDict2OperationCompleted);
            }
            this.InvokeAsync("GetPricesAndSignsDict2", new object[] {
                        login,
                        password,
                        priceLogo,
                        destinationLogo}, this.GetPricesAndSignsDict2OperationCompleted, userState);
        }
        
        private void OnGetPricesAndSignsDict2OperationCompleted(object arg) {
            if ((this.GetPricesAndSignsDict2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPricesAndSignsDict2Completed(this, new GetPricesAndSignsDict2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPricesAndSignsDict", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PriceAndSigns[] GetPricesAndSignsDict(long login, string password, string priceLogo, string destinationLogo) {
            object[] results = this.Invoke("GetPricesAndSignsDict", new object[] {
                        login,
                        password,
                        priceLogo,
                        destinationLogo});
            return ((PriceAndSigns[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPricesAndSignsDictAsync(long login, string password, string priceLogo, string destinationLogo) {
            this.GetPricesAndSignsDictAsync(login, password, priceLogo, destinationLogo, null);
        }
        
        /// <remarks/>
        public void GetPricesAndSignsDictAsync(long login, string password, string priceLogo, string destinationLogo, object userState) {
            if ((this.GetPricesAndSignsDictOperationCompleted == null)) {
                this.GetPricesAndSignsDictOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPricesAndSignsDictOperationCompleted);
            }
            this.InvokeAsync("GetPricesAndSignsDict", new object[] {
                        login,
                        password,
                        priceLogo,
                        destinationLogo}, this.GetPricesAndSignsDictOperationCompleted, userState);
        }
        
        private void OnGetPricesAndSignsDictOperationCompleted(object arg) {
            if ((this.GetPricesAndSignsDictCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPricesAndSignsDictCompleted(this, new GetPricesAndSignsDictCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetConsumersDict_Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsumerInfo[] GetConsumersDict_Test(long login, string password, string consumerIdString) {
            object[] results = this.Invoke("GetConsumersDict_Test", new object[] {
                        login,
                        password,
                        consumerIdString});
            return ((ConsumerInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetConsumersDict_TestAsync(long login, string password, string consumerIdString) {
            this.GetConsumersDict_TestAsync(login, password, consumerIdString, null);
        }
        
        /// <remarks/>
        public void GetConsumersDict_TestAsync(long login, string password, string consumerIdString, object userState) {
            if ((this.GetConsumersDict_TestOperationCompleted == null)) {
                this.GetConsumersDict_TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConsumersDict_TestOperationCompleted);
            }
            this.InvokeAsync("GetConsumersDict_Test", new object[] {
                        login,
                        password,
                        consumerIdString}, this.GetConsumersDict_TestOperationCompleted, userState);
        }
        
        private void OnGetConsumersDict_TestOperationCompleted(object arg) {
            if ((this.GetConsumersDict_TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConsumersDict_TestCompleted(this, new GetConsumersDict_TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestConnect", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestConnect(string s) {
            object[] results = this.Invoke("TestConnect", new object[] {
                        s});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestConnectAsync(string s) {
            this.TestConnectAsync(s, null);
        }
        
        /// <remarks/>
        public void TestConnectAsync(string s, object userState) {
            if ((this.TestConnectOperationCompleted == null)) {
                this.TestConnectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestConnectOperationCompleted);
            }
            this.InvokeAsync("TestConnect", new object[] {
                        s}, this.TestConnectOperationCompleted, userState);
        }
        
        private void OnTestConnectOperationCompleted(object arg) {
            if ((this.TestConnectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestConnectCompleted(this, new TestConnectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ShortMakeInfo {
        
        private string makeLogoField;
        
        private string makeNameField;
        
        /// <remarks/>
        public string MakeLogo {
            get {
                return this.makeLogoField;
            }
            set {
                this.makeLogoField = value;
            }
        }
        
        /// <remarks/>
        public string MakeName {
            get {
                return this.makeNameField;
            }
            set {
                this.makeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PriceAndSigns {
        
        private string priceLogoField;
        
        private string priceDescField;
        
        private string destinationLogoField;
        
        private string destinationDescField;
        
        private string priceDescPublicFullField;
        
        private short daysField;
        
        private short deliverTimeGuaranteedField;
        
        private PriceSigns originalSignsField;
        
        private PriceSigns notOriginalSignsField;
        
        /// <remarks/>
        public string PriceLogo {
            get {
                return this.priceLogoField;
            }
            set {
                this.priceLogoField = value;
            }
        }
        
        /// <remarks/>
        public string PriceDesc {
            get {
                return this.priceDescField;
            }
            set {
                this.priceDescField = value;
            }
        }
        
        /// <remarks/>
        public string DestinationLogo {
            get {
                return this.destinationLogoField;
            }
            set {
                this.destinationLogoField = value;
            }
        }
        
        /// <remarks/>
        public string DestinationDesc {
            get {
                return this.destinationDescField;
            }
            set {
                this.destinationDescField = value;
            }
        }
        
        /// <remarks/>
        public string PriceDescPublicFull {
            get {
                return this.priceDescPublicFullField;
            }
            set {
                this.priceDescPublicFullField = value;
            }
        }
        
        /// <remarks/>
        public short Days {
            get {
                return this.daysField;
            }
            set {
                this.daysField = value;
            }
        }
        
        /// <remarks/>
        public short DeliverTimeGuaranteed {
            get {
                return this.deliverTimeGuaranteedField;
            }
            set {
                this.deliverTimeGuaranteedField = value;
            }
        }
        
        /// <remarks/>
        public PriceSigns OriginalSigns {
            get {
                return this.originalSignsField;
            }
            set {
                this.originalSignsField = value;
            }
        }
        
        /// <remarks/>
        public PriceSigns NotOriginalSigns {
            get {
                return this.notOriginalSignsField;
            }
            set {
                this.notOriginalSignsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PriceSigns {
        
        private bool oNLYField;
        
        private bool bRANDField;
        
        private bool qUANField;
        
        private bool uNITField;
        
        private bool wAITField;
        
        /// <remarks/>
        public bool ONLY {
            get {
                return this.oNLYField;
            }
            set {
                this.oNLYField = value;
            }
        }
        
        /// <remarks/>
        public bool BRAND {
            get {
                return this.bRANDField;
            }
            set {
                this.bRANDField = value;
            }
        }
        
        /// <remarks/>
        public bool QUAN {
            get {
                return this.qUANField;
            }
            set {
                this.qUANField = value;
            }
        }
        
        /// <remarks/>
        public bool UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
            }
        }
        
        /// <remarks/>
        public bool WAIT {
            get {
                return this.wAITField;
            }
            set {
                this.wAITField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PriceAndSigns2 {
        
        private string priceLogoField;
        
        private string priceDescField;
        
        private string destinationLogoField;
        
        private string destinationDescField;
        
        private string priceDescPublicFullField;
        
        private PriceSigns originalSignsField;
        
        private PriceSigns notOriginalSignsField;
        
        /// <remarks/>
        public string PriceLogo {
            get {
                return this.priceLogoField;
            }
            set {
                this.priceLogoField = value;
            }
        }
        
        /// <remarks/>
        public string PriceDesc {
            get {
                return this.priceDescField;
            }
            set {
                this.priceDescField = value;
            }
        }
        
        /// <remarks/>
        public string DestinationLogo {
            get {
                return this.destinationLogoField;
            }
            set {
                this.destinationLogoField = value;
            }
        }
        
        /// <remarks/>
        public string DestinationDesc {
            get {
                return this.destinationDescField;
            }
            set {
                this.destinationDescField = value;
            }
        }
        
        /// <remarks/>
        public string PriceDescPublicFull {
            get {
                return this.priceDescPublicFullField;
            }
            set {
                this.priceDescPublicFullField = value;
            }
        }
        
        /// <remarks/>
        public PriceSigns OriginalSigns {
            get {
                return this.originalSignsField;
            }
            set {
                this.originalSignsField = value;
            }
        }
        
        /// <remarks/>
        public PriceSigns NotOriginalSigns {
            get {
                return this.notOriginalSignsField;
            }
            set {
                this.notOriginalSignsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsumerInfo {
        
        private long userIdField;
        
        private long consumerIdField;
        
        private string userFamilyField;
        
        private string userFirstNameField;
        
        private string userLastNameField;
        
        private string userLogoField;
        
        private long locationIdField;
        
        private string locationAddressField;
        
        private string locationAddressAdditionalField;
        
        private long optovikManagerIdField;
        
        private string optovikManagerFioField;
        
        /// <remarks/>
        public long UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public long ConsumerId {
            get {
                return this.consumerIdField;
            }
            set {
                this.consumerIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserFamily {
            get {
                return this.userFamilyField;
            }
            set {
                this.userFamilyField = value;
            }
        }
        
        /// <remarks/>
        public string UserFirstName {
            get {
                return this.userFirstNameField;
            }
            set {
                this.userFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserLastName {
            get {
                return this.userLastNameField;
            }
            set {
                this.userLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserLogo {
            get {
                return this.userLogoField;
            }
            set {
                this.userLogoField = value;
            }
        }
        
        /// <remarks/>
        public long LocationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        public string LocationAddress {
            get {
                return this.locationAddressField;
            }
            set {
                this.locationAddressField = value;
            }
        }
        
        /// <remarks/>
        public string LocationAddressAdditional {
            get {
                return this.locationAddressAdditionalField;
            }
            set {
                this.locationAddressAdditionalField = value;
            }
        }
        
        /// <remarks/>
        public long OptovikManagerId {
            get {
                return this.optovikManagerIdField;
            }
            set {
                this.optovikManagerIdField = value;
            }
        }
        
        /// <remarks/>
        public string OptovikManagerFio {
            get {
                return this.optovikManagerFioField;
            }
            set {
                this.optovikManagerFioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetMakesDictCompletedEventHandler(object sender, GetMakesDictCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMakesDictCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMakesDictCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ShortMakeInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ShortMakeInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetConsumersDictCompletedEventHandler(object sender, GetConsumersDictCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConsumersDictCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConsumersDictCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsumerInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsumerInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetPricesAndSignsDict2CompletedEventHandler(object sender, GetPricesAndSignsDict2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPricesAndSignsDict2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPricesAndSignsDict2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PriceAndSigns2[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PriceAndSigns2[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetPricesAndSignsDictCompletedEventHandler(object sender, GetPricesAndSignsDictCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPricesAndSignsDictCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPricesAndSignsDictCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PriceAndSigns[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PriceAndSigns[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetConsumersDict_TestCompletedEventHandler(object sender, GetConsumersDict_TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConsumersDict_TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConsumersDict_TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsumerInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsumerInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TestConnectCompletedEventHandler(object sender, TestConnectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestConnectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestConnectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591