//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EmexApp.EmExInmotion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EmExInmotionSoap", Namespace="http://tempuri.org/")]
    public partial class EmExInmotion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetWholesalerInmotionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConsumerInmotionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConsumerInmotion3OperationCompleted;
        
        private System.Threading.SendOrPostCallback InMotion_SubIdByGlobalIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetInmotionStateByGlobalIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetInmotionStateBySubIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWholesalerInmotion_TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConsumerInmotion_TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConsumerInmotion3_TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestConnectOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EmExInmotion() {
            this.Url = global::EmexApp.Properties.Settings.Default.EmexApp_EmExInmotion_EmExInmotion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetWholesalerInmotionCompletedEventHandler GetWholesalerInmotionCompleted;
        
        /// <remarks/>
        public event GetConsumerInmotionCompletedEventHandler GetConsumerInmotionCompleted;
        
        /// <remarks/>
        public event GetConsumerInmotion3CompletedEventHandler GetConsumerInmotion3Completed;
        
        /// <remarks/>
        public event InMotion_SubIdByGlobalIdCompletedEventHandler InMotion_SubIdByGlobalIdCompleted;
        
        /// <remarks/>
        public event SetInmotionStateByGlobalIdCompletedEventHandler SetInmotionStateByGlobalIdCompleted;
        
        /// <remarks/>
        public event SetInmotionStateBySubIdCompletedEventHandler SetInmotionStateBySubIdCompleted;
        
        /// <remarks/>
        public event GetWholesalerInmotion_TestCompletedEventHandler GetWholesalerInmotion_TestCompleted;
        
        /// <remarks/>
        public event GetConsumerInmotion_TestCompletedEventHandler GetConsumerInmotion_TestCompleted;
        
        /// <remarks/>
        public event GetConsumerInmotion3_TestCompletedEventHandler GetConsumerInmotion3_TestCompleted;
        
        /// <remarks/>
        public event TestConnectCompletedEventHandler TestConnectCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWholesalerInmotion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InmWholesaler_v2[] GetWholesalerInmotion(long login, string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> beginDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> endDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> greaterThenGlobalId, long[] globalIds, int[] states, string reference, string detailNum, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] timestamp, bool activeOnly) {
            object[] results = this.Invoke("GetWholesalerInmotion", new object[] {
                        login,
                        password,
                        beginDate,
                        endDate,
                        greaterThenGlobalId,
                        globalIds,
                        states,
                        reference,
                        detailNum,
                        timestamp,
                        activeOnly});
            return ((InmWholesaler_v2[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWholesalerInmotionAsync(long login, string password, System.Nullable<System.DateTime> beginDate, System.Nullable<System.DateTime> endDate, System.Nullable<long> greaterThenGlobalId, long[] globalIds, int[] states, string reference, string detailNum, byte[] timestamp, bool activeOnly) {
            this.GetWholesalerInmotionAsync(login, password, beginDate, endDate, greaterThenGlobalId, globalIds, states, reference, detailNum, timestamp, activeOnly, null);
        }
        
        /// <remarks/>
        public void GetWholesalerInmotionAsync(long login, string password, System.Nullable<System.DateTime> beginDate, System.Nullable<System.DateTime> endDate, System.Nullable<long> greaterThenGlobalId, long[] globalIds, int[] states, string reference, string detailNum, byte[] timestamp, bool activeOnly, object userState) {
            if ((this.GetWholesalerInmotionOperationCompleted == null)) {
                this.GetWholesalerInmotionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWholesalerInmotionOperationCompleted);
            }
            this.InvokeAsync("GetWholesalerInmotion", new object[] {
                        login,
                        password,
                        beginDate,
                        endDate,
                        greaterThenGlobalId,
                        globalIds,
                        states,
                        reference,
                        detailNum,
                        timestamp,
                        activeOnly}, this.GetWholesalerInmotionOperationCompleted, userState);
        }
        
        private void OnGetWholesalerInmotionOperationCompleted(object arg) {
            if ((this.GetWholesalerInmotionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWholesalerInmotionCompleted(this, new GetWholesalerInmotionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetConsumerInmotion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InmConsumer_v2[] GetConsumerInmotion(long login, string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> beginDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> endDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> greaterThenGlobalId, long[] globalIds, int[] states, string reference, string detailNum, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] timestamp, bool activeOnly) {
            object[] results = this.Invoke("GetConsumerInmotion", new object[] {
                        login,
                        password,
                        beginDate,
                        endDate,
                        greaterThenGlobalId,
                        globalIds,
                        states,
                        reference,
                        detailNum,
                        timestamp,
                        activeOnly});
            return ((InmConsumer_v2[])(results[0]));
        }
        
        /// <remarks/>
        public void GetConsumerInmotionAsync(long login, string password, System.Nullable<System.DateTime> beginDate, System.Nullable<System.DateTime> endDate, System.Nullable<long> greaterThenGlobalId, long[] globalIds, int[] states, string reference, string detailNum, byte[] timestamp, bool activeOnly) {
            this.GetConsumerInmotionAsync(login, password, beginDate, endDate, greaterThenGlobalId, globalIds, states, reference, detailNum, timestamp, activeOnly, null);
        }
        
        /// <remarks/>
        public void GetConsumerInmotionAsync(long login, string password, System.Nullable<System.DateTime> beginDate, System.Nullable<System.DateTime> endDate, System.Nullable<long> greaterThenGlobalId, long[] globalIds, int[] states, string reference, string detailNum, byte[] timestamp, bool activeOnly, object userState) {
            if ((this.GetConsumerInmotionOperationCompleted == null)) {
                this.GetConsumerInmotionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConsumerInmotionOperationCompleted);
            }
            this.InvokeAsync("GetConsumerInmotion", new object[] {
                        login,
                        password,
                        beginDate,
                        endDate,
                        greaterThenGlobalId,
                        globalIds,
                        states,
                        reference,
                        detailNum,
                        timestamp,
                        activeOnly}, this.GetConsumerInmotionOperationCompleted, userState);
        }
        
        private void OnGetConsumerInmotionOperationCompleted(object arg) {
            if ((this.GetConsumerInmotionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConsumerInmotionCompleted(this, new GetConsumerInmotionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetConsumerInmotion3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InmConsumer_v3[] GetConsumerInmotion3(long login, string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> beginDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> endDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> greaterThenGlobalId, long[] globalIds, int[] states, string reference, string detailNum, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] timestamp, bool activeOnly) {
            object[] results = this.Invoke("GetConsumerInmotion3", new object[] {
                        login,
                        password,
                        beginDate,
                        endDate,
                        greaterThenGlobalId,
                        globalIds,
                        states,
                        reference,
                        detailNum,
                        timestamp,
                        activeOnly});
            return ((InmConsumer_v3[])(results[0]));
        }
        
        /// <remarks/>
        public void GetConsumerInmotion3Async(long login, string password, System.Nullable<System.DateTime> beginDate, System.Nullable<System.DateTime> endDate, System.Nullable<long> greaterThenGlobalId, long[] globalIds, int[] states, string reference, string detailNum, byte[] timestamp, bool activeOnly) {
            this.GetConsumerInmotion3Async(login, password, beginDate, endDate, greaterThenGlobalId, globalIds, states, reference, detailNum, timestamp, activeOnly, null);
        }
        
        /// <remarks/>
        public void GetConsumerInmotion3Async(long login, string password, System.Nullable<System.DateTime> beginDate, System.Nullable<System.DateTime> endDate, System.Nullable<long> greaterThenGlobalId, long[] globalIds, int[] states, string reference, string detailNum, byte[] timestamp, bool activeOnly, object userState) {
            if ((this.GetConsumerInmotion3OperationCompleted == null)) {
                this.GetConsumerInmotion3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConsumerInmotion3OperationCompleted);
            }
            this.InvokeAsync("GetConsumerInmotion3", new object[] {
                        login,
                        password,
                        beginDate,
                        endDate,
                        greaterThenGlobalId,
                        globalIds,
                        states,
                        reference,
                        detailNum,
                        timestamp,
                        activeOnly}, this.GetConsumerInmotion3OperationCompleted, userState);
        }
        
        private void OnGetConsumerInmotion3OperationCompleted(object arg) {
            if ((this.GetConsumerInmotion3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConsumerInmotion3Completed(this, new GetConsumerInmotion3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InMotion_SubIdByGlobalId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long[] InMotion_SubIdByGlobalId(long login, string password, long GlobalId) {
            object[] results = this.Invoke("InMotion_SubIdByGlobalId", new object[] {
                        login,
                        password,
                        GlobalId});
            return ((long[])(results[0]));
        }
        
        /// <remarks/>
        public void InMotion_SubIdByGlobalIdAsync(long login, string password, long GlobalId) {
            this.InMotion_SubIdByGlobalIdAsync(login, password, GlobalId, null);
        }
        
        /// <remarks/>
        public void InMotion_SubIdByGlobalIdAsync(long login, string password, long GlobalId, object userState) {
            if ((this.InMotion_SubIdByGlobalIdOperationCompleted == null)) {
                this.InMotion_SubIdByGlobalIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInMotion_SubIdByGlobalIdOperationCompleted);
            }
            this.InvokeAsync("InMotion_SubIdByGlobalId", new object[] {
                        login,
                        password,
                        GlobalId}, this.InMotion_SubIdByGlobalIdOperationCompleted, userState);
        }
        
        private void OnInMotion_SubIdByGlobalIdOperationCompleted(object arg) {
            if ((this.InMotion_SubIdByGlobalIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InMotion_SubIdByGlobalIdCompleted(this, new InMotion_SubIdByGlobalIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetInmotionStateByGlobalId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SetInmotionStateByGlobalIdOutputItem[] SetInmotionStateByGlobalId(long login, string password, SetInmotionStateByGlobalIdInputItem[] setInmotionStateItems) {
            object[] results = this.Invoke("SetInmotionStateByGlobalId", new object[] {
                        login,
                        password,
                        setInmotionStateItems});
            return ((SetInmotionStateByGlobalIdOutputItem[])(results[0]));
        }
        
        /// <remarks/>
        public void SetInmotionStateByGlobalIdAsync(long login, string password, SetInmotionStateByGlobalIdInputItem[] setInmotionStateItems) {
            this.SetInmotionStateByGlobalIdAsync(login, password, setInmotionStateItems, null);
        }
        
        /// <remarks/>
        public void SetInmotionStateByGlobalIdAsync(long login, string password, SetInmotionStateByGlobalIdInputItem[] setInmotionStateItems, object userState) {
            if ((this.SetInmotionStateByGlobalIdOperationCompleted == null)) {
                this.SetInmotionStateByGlobalIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetInmotionStateByGlobalIdOperationCompleted);
            }
            this.InvokeAsync("SetInmotionStateByGlobalId", new object[] {
                        login,
                        password,
                        setInmotionStateItems}, this.SetInmotionStateByGlobalIdOperationCompleted, userState);
        }
        
        private void OnSetInmotionStateByGlobalIdOperationCompleted(object arg) {
            if ((this.SetInmotionStateByGlobalIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetInmotionStateByGlobalIdCompleted(this, new SetInmotionStateByGlobalIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetInmotionStateBySubId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SetInmotionStateBySubIdOutputItem[] SetInmotionStateBySubId(long login, string password, SetInmotionStateBySubIdInputItem[] setInmotionStateItems) {
            object[] results = this.Invoke("SetInmotionStateBySubId", new object[] {
                        login,
                        password,
                        setInmotionStateItems});
            return ((SetInmotionStateBySubIdOutputItem[])(results[0]));
        }
        
        /// <remarks/>
        public void SetInmotionStateBySubIdAsync(long login, string password, SetInmotionStateBySubIdInputItem[] setInmotionStateItems) {
            this.SetInmotionStateBySubIdAsync(login, password, setInmotionStateItems, null);
        }
        
        /// <remarks/>
        public void SetInmotionStateBySubIdAsync(long login, string password, SetInmotionStateBySubIdInputItem[] setInmotionStateItems, object userState) {
            if ((this.SetInmotionStateBySubIdOperationCompleted == null)) {
                this.SetInmotionStateBySubIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetInmotionStateBySubIdOperationCompleted);
            }
            this.InvokeAsync("SetInmotionStateBySubId", new object[] {
                        login,
                        password,
                        setInmotionStateItems}, this.SetInmotionStateBySubIdOperationCompleted, userState);
        }
        
        private void OnSetInmotionStateBySubIdOperationCompleted(object arg) {
            if ((this.SetInmotionStateBySubIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetInmotionStateBySubIdCompleted(this, new SetInmotionStateBySubIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWholesalerInmotion_Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InmWholesaler_v2[] GetWholesalerInmotion_Test(long login, string password, string beginDateString, string endDateString, string greaterThenGlobalIdString, string globalIdsString, string statesString, string reference, string detailNum, string timestampString, bool activeOnly) {
            object[] results = this.Invoke("GetWholesalerInmotion_Test", new object[] {
                        login,
                        password,
                        beginDateString,
                        endDateString,
                        greaterThenGlobalIdString,
                        globalIdsString,
                        statesString,
                        reference,
                        detailNum,
                        timestampString,
                        activeOnly});
            return ((InmWholesaler_v2[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWholesalerInmotion_TestAsync(long login, string password, string beginDateString, string endDateString, string greaterThenGlobalIdString, string globalIdsString, string statesString, string reference, string detailNum, string timestampString, bool activeOnly) {
            this.GetWholesalerInmotion_TestAsync(login, password, beginDateString, endDateString, greaterThenGlobalIdString, globalIdsString, statesString, reference, detailNum, timestampString, activeOnly, null);
        }
        
        /// <remarks/>
        public void GetWholesalerInmotion_TestAsync(long login, string password, string beginDateString, string endDateString, string greaterThenGlobalIdString, string globalIdsString, string statesString, string reference, string detailNum, string timestampString, bool activeOnly, object userState) {
            if ((this.GetWholesalerInmotion_TestOperationCompleted == null)) {
                this.GetWholesalerInmotion_TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWholesalerInmotion_TestOperationCompleted);
            }
            this.InvokeAsync("GetWholesalerInmotion_Test", new object[] {
                        login,
                        password,
                        beginDateString,
                        endDateString,
                        greaterThenGlobalIdString,
                        globalIdsString,
                        statesString,
                        reference,
                        detailNum,
                        timestampString,
                        activeOnly}, this.GetWholesalerInmotion_TestOperationCompleted, userState);
        }
        
        private void OnGetWholesalerInmotion_TestOperationCompleted(object arg) {
            if ((this.GetWholesalerInmotion_TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWholesalerInmotion_TestCompleted(this, new GetWholesalerInmotion_TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetConsumerInmotion_Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InmConsumer_v2[] GetConsumerInmotion_Test(long login, string password, string beginDateString, string endDateString, string greaterThenGlobalIdString, string globalIdsString, string statesString, string reference, string detailNum, string timestampString, bool activeOnly) {
            object[] results = this.Invoke("GetConsumerInmotion_Test", new object[] {
                        login,
                        password,
                        beginDateString,
                        endDateString,
                        greaterThenGlobalIdString,
                        globalIdsString,
                        statesString,
                        reference,
                        detailNum,
                        timestampString,
                        activeOnly});
            return ((InmConsumer_v2[])(results[0]));
        }
        
        /// <remarks/>
        public void GetConsumerInmotion_TestAsync(long login, string password, string beginDateString, string endDateString, string greaterThenGlobalIdString, string globalIdsString, string statesString, string reference, string detailNum, string timestampString, bool activeOnly) {
            this.GetConsumerInmotion_TestAsync(login, password, beginDateString, endDateString, greaterThenGlobalIdString, globalIdsString, statesString, reference, detailNum, timestampString, activeOnly, null);
        }
        
        /// <remarks/>
        public void GetConsumerInmotion_TestAsync(long login, string password, string beginDateString, string endDateString, string greaterThenGlobalIdString, string globalIdsString, string statesString, string reference, string detailNum, string timestampString, bool activeOnly, object userState) {
            if ((this.GetConsumerInmotion_TestOperationCompleted == null)) {
                this.GetConsumerInmotion_TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConsumerInmotion_TestOperationCompleted);
            }
            this.InvokeAsync("GetConsumerInmotion_Test", new object[] {
                        login,
                        password,
                        beginDateString,
                        endDateString,
                        greaterThenGlobalIdString,
                        globalIdsString,
                        statesString,
                        reference,
                        detailNum,
                        timestampString,
                        activeOnly}, this.GetConsumerInmotion_TestOperationCompleted, userState);
        }
        
        private void OnGetConsumerInmotion_TestOperationCompleted(object arg) {
            if ((this.GetConsumerInmotion_TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConsumerInmotion_TestCompleted(this, new GetConsumerInmotion_TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetConsumerInmotion3_Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InmConsumer_v3[] GetConsumerInmotion3_Test(long login, string password, string beginDateString, string endDateString, string greaterThenGlobalIdString, string globalIdsString, string statesString, string reference, string detailNum, string timestampString, bool activeOnly) {
            object[] results = this.Invoke("GetConsumerInmotion3_Test", new object[] {
                        login,
                        password,
                        beginDateString,
                        endDateString,
                        greaterThenGlobalIdString,
                        globalIdsString,
                        statesString,
                        reference,
                        detailNum,
                        timestampString,
                        activeOnly});
            return ((InmConsumer_v3[])(results[0]));
        }
        
        /// <remarks/>
        public void GetConsumerInmotion3_TestAsync(long login, string password, string beginDateString, string endDateString, string greaterThenGlobalIdString, string globalIdsString, string statesString, string reference, string detailNum, string timestampString, bool activeOnly) {
            this.GetConsumerInmotion3_TestAsync(login, password, beginDateString, endDateString, greaterThenGlobalIdString, globalIdsString, statesString, reference, detailNum, timestampString, activeOnly, null);
        }
        
        /// <remarks/>
        public void GetConsumerInmotion3_TestAsync(long login, string password, string beginDateString, string endDateString, string greaterThenGlobalIdString, string globalIdsString, string statesString, string reference, string detailNum, string timestampString, bool activeOnly, object userState) {
            if ((this.GetConsumerInmotion3_TestOperationCompleted == null)) {
                this.GetConsumerInmotion3_TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConsumerInmotion3_TestOperationCompleted);
            }
            this.InvokeAsync("GetConsumerInmotion3_Test", new object[] {
                        login,
                        password,
                        beginDateString,
                        endDateString,
                        greaterThenGlobalIdString,
                        globalIdsString,
                        statesString,
                        reference,
                        detailNum,
                        timestampString,
                        activeOnly}, this.GetConsumerInmotion3_TestOperationCompleted, userState);
        }
        
        private void OnGetConsumerInmotion3_TestOperationCompleted(object arg) {
            if ((this.GetConsumerInmotion3_TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConsumerInmotion3_TestCompleted(this, new GetConsumerInmotion3_TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestConnect", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestConnect(string s) {
            object[] results = this.Invoke("TestConnect", new object[] {
                        s});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestConnectAsync(string s) {
            this.TestConnectAsync(s, null);
        }
        
        /// <remarks/>
        public void TestConnectAsync(string s, object userState) {
            if ((this.TestConnectOperationCompleted == null)) {
                this.TestConnectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestConnectOperationCompleted);
            }
            this.InvokeAsync("TestConnect", new object[] {
                        s}, this.TestConnectOperationCompleted, userState);
        }
        
        private void OnTestConnectOperationCompleted(object arg) {
            if ((this.TestConnectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestConnectCompleted(this, new TestConnectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InmWholesaler_v2 : InmConsumer_v2 {
        
        private System.Nullable<decimal> accPriceOrdOptRURField;
        
        private System.Nullable<decimal> accPriceLastOptRURField;
        
        private System.Nullable<decimal> accPriceOptFullRURField;
        
        private System.Nullable<decimal> accPriceOptCreditPayRURField;
        
        private System.Nullable<decimal> accRegPriceOptField;
        
        private System.Nullable<decimal> accRegPriceOptRURField;
        
        private System.Nullable<decimal> ansPriceOptRURField;
        
        private System.Nullable<decimal> coeffMaxAGREEField;
        
        private System.Nullable<decimal> defPriceOptField;
        
        private System.Nullable<decimal> defPriceOptRURField;
        
        private string optovikReferenceField;
        
        private System.Nullable<decimal> ordPriceOptField;
        
        private System.Nullable<decimal> ordPriceOptRURField;
        
        private System.Nullable<System.DateTime> pOrdDateField;
        
        private System.Nullable<byte> priceRuleField;
        
        private System.Nullable<decimal> priceOptPrevRURField;
        
        private byte priceModifierField;
        
        private System.Nullable<decimal> recRegPriceOptField;
        
        private System.Nullable<decimal> recRegPriceOptRURField;
        
        private System.Nullable<decimal> storePayField;
        
        private System.Nullable<decimal> storePayFactField;
        
        private byte[] timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> AccPriceOrdOptRUR {
            get {
                return this.accPriceOrdOptRURField;
            }
            set {
                this.accPriceOrdOptRURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> AccPriceLastOptRUR {
            get {
                return this.accPriceLastOptRURField;
            }
            set {
                this.accPriceLastOptRURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> AccPriceOptFullRUR {
            get {
                return this.accPriceOptFullRURField;
            }
            set {
                this.accPriceOptFullRURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> AccPriceOptCreditPayRUR {
            get {
                return this.accPriceOptCreditPayRURField;
            }
            set {
                this.accPriceOptCreditPayRURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> AccRegPriceOpt {
            get {
                return this.accRegPriceOptField;
            }
            set {
                this.accRegPriceOptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> AccRegPriceOptRUR {
            get {
                return this.accRegPriceOptRURField;
            }
            set {
                this.accRegPriceOptRURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> AnsPriceOptRUR {
            get {
                return this.ansPriceOptRURField;
            }
            set {
                this.ansPriceOptRURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> CoeffMaxAGREE {
            get {
                return this.coeffMaxAGREEField;
            }
            set {
                this.coeffMaxAGREEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> DefPriceOpt {
            get {
                return this.defPriceOptField;
            }
            set {
                this.defPriceOptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> DefPriceOptRUR {
            get {
                return this.defPriceOptRURField;
            }
            set {
                this.defPriceOptRURField = value;
            }
        }
        
        /// <remarks/>
        public string OptovikReference {
            get {
                return this.optovikReferenceField;
            }
            set {
                this.optovikReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> OrdPriceOpt {
            get {
                return this.ordPriceOptField;
            }
            set {
                this.ordPriceOptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> OrdPriceOptRUR {
            get {
                return this.ordPriceOptRURField;
            }
            set {
                this.ordPriceOptRURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> POrdDate {
            get {
                return this.pOrdDateField;
            }
            set {
                this.pOrdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> PriceRule {
            get {
                return this.priceRuleField;
            }
            set {
                this.priceRuleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PriceOptPrevRUR {
            get {
                return this.priceOptPrevRURField;
            }
            set {
                this.priceOptPrevRURField = value;
            }
        }
        
        /// <remarks/>
        public byte PriceModifier {
            get {
                return this.priceModifierField;
            }
            set {
                this.priceModifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> RecRegPriceOpt {
            get {
                return this.recRegPriceOptField;
            }
            set {
                this.recRegPriceOptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> RecRegPriceOptRUR {
            get {
                return this.recRegPriceOptRURField;
            }
            set {
                this.recRegPriceOptRURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> StorePay {
            get {
                return this.storePayField;
            }
            set {
                this.storePayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> StorePayFact {
            get {
                return this.storePayFactField;
            }
            set {
                this.storePayFactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InmConsumer_v3))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InmWholesaler_v2))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InmConsumer_v2 {
        
        private System.Nullable<decimal> accPriceOrdPotrRURField;
        
        private System.Nullable<decimal> accPriceLastPotrRURField;
        
        private System.Nullable<System.DateTime> accDateField;
        
        private System.Nullable<short> accQuantityField;
        
        private System.Nullable<System.DateTime> accRegDateField;
        
        private System.Nullable<short> accRegQuantityField;
        
        private System.Nullable<System.DateTime> ansDateField;
        
        private System.Nullable<short> ansQuantityField;
        
        private bool bitONLYField;
        
        private bool bitQUANField;
        
        private bool bitUNITField;
        
        private bool bitAGREField;
        
        private bool bitNOTCField;
        
        private bool bitWAITSTOCField;
        
        private bool bitWAITField;
        
        private bool bitBRANDField;
        
        private bool bitREZEField;
        
        private byte deliverTimeAverageField;
        
        private byte deliverTimeGuaranteeField;
        
        private string detailNumField;
        
        private string detailNameRusUserField;
        
        private string destinationLogoField;
        
        private short detailQuantityField;
        
        private System.Nullable<short> denyQuantityField;
        
        private System.Nullable<System.DateTime> defDateField;
        
        private System.Nullable<short> defQuantityField;
        
        private long globalIdField;
        
        private System.Nullable<System.DateTime> invDateField;
        
        private System.Nullable<short> invQuantityField;
        
        private string makeLogoField;
        
        private string makeNameField;
        
        private System.Nullable<System.DateTime> ordDateField;
        
        private System.Nullable<short> ordQuantityField;
        
        private string optovikLogoField;
        
        private long potrebitelIdField;
        
        private string potrebitelReferenceField;
        
        private string priceLogoField;
        
        private System.Nullable<short> pOrdQuantityField;
        
        private string potrebitelNameField;
        
        private string potrebitelLogoField;
        
        private System.Nullable<decimal> pricePotPrevRURField;
        
        private System.Nullable<int> questionsCountField;
        
        private System.Nullable<System.DateTime> recDateField;
        
        private System.Nullable<short> recQuantityField;
        
        private System.Nullable<System.DateTime> recRegDateField;
        
        private System.Nullable<short> recRegQuantityField;
        
        private System.Nullable<byte> stateField;
        
        private string substMakeLogoField;
        
        private string substMakeNameField;
        
        private string substDetailNumField;
        
        private System.Nullable<System.DateTime> storeDatePlanField;
        
        private System.Nullable<System.DateTime> storeDateFactField;
        
        private long userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> AccPriceOrdPotrRUR {
            get {
                return this.accPriceOrdPotrRURField;
            }
            set {
                this.accPriceOrdPotrRURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> AccPriceLastPotrRUR {
            get {
                return this.accPriceLastPotrRURField;
            }
            set {
                this.accPriceLastPotrRURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> AccDate {
            get {
                return this.accDateField;
            }
            set {
                this.accDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> AccQuantity {
            get {
                return this.accQuantityField;
            }
            set {
                this.accQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> AccRegDate {
            get {
                return this.accRegDateField;
            }
            set {
                this.accRegDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> AccRegQuantity {
            get {
                return this.accRegQuantityField;
            }
            set {
                this.accRegQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> AnsDate {
            get {
                return this.ansDateField;
            }
            set {
                this.ansDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> AnsQuantity {
            get {
                return this.ansQuantityField;
            }
            set {
                this.ansQuantityField = value;
            }
        }
        
        /// <remarks/>
        public bool bitONLY {
            get {
                return this.bitONLYField;
            }
            set {
                this.bitONLYField = value;
            }
        }
        
        /// <remarks/>
        public bool bitQUAN {
            get {
                return this.bitQUANField;
            }
            set {
                this.bitQUANField = value;
            }
        }
        
        /// <remarks/>
        public bool bitUNIT {
            get {
                return this.bitUNITField;
            }
            set {
                this.bitUNITField = value;
            }
        }
        
        /// <remarks/>
        public bool bitAGRE {
            get {
                return this.bitAGREField;
            }
            set {
                this.bitAGREField = value;
            }
        }
        
        /// <remarks/>
        public bool bitNOTC {
            get {
                return this.bitNOTCField;
            }
            set {
                this.bitNOTCField = value;
            }
        }
        
        /// <remarks/>
        public bool bitWAITSTOC {
            get {
                return this.bitWAITSTOCField;
            }
            set {
                this.bitWAITSTOCField = value;
            }
        }
        
        /// <remarks/>
        public bool bitWAIT {
            get {
                return this.bitWAITField;
            }
            set {
                this.bitWAITField = value;
            }
        }
        
        /// <remarks/>
        public bool bitBRAND {
            get {
                return this.bitBRANDField;
            }
            set {
                this.bitBRANDField = value;
            }
        }
        
        /// <remarks/>
        public bool bitREZE {
            get {
                return this.bitREZEField;
            }
            set {
                this.bitREZEField = value;
            }
        }
        
        /// <remarks/>
        public byte DeliverTimeAverage {
            get {
                return this.deliverTimeAverageField;
            }
            set {
                this.deliverTimeAverageField = value;
            }
        }
        
        /// <remarks/>
        public byte DeliverTimeGuarantee {
            get {
                return this.deliverTimeGuaranteeField;
            }
            set {
                this.deliverTimeGuaranteeField = value;
            }
        }
        
        /// <remarks/>
        public string DetailNum {
            get {
                return this.detailNumField;
            }
            set {
                this.detailNumField = value;
            }
        }
        
        /// <remarks/>
        public string DetailNameRusUser {
            get {
                return this.detailNameRusUserField;
            }
            set {
                this.detailNameRusUserField = value;
            }
        }
        
        /// <remarks/>
        public string DestinationLogo {
            get {
                return this.destinationLogoField;
            }
            set {
                this.destinationLogoField = value;
            }
        }
        
        /// <remarks/>
        public short DetailQuantity {
            get {
                return this.detailQuantityField;
            }
            set {
                this.detailQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> DenyQuantity {
            get {
                return this.denyQuantityField;
            }
            set {
                this.denyQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DefDate {
            get {
                return this.defDateField;
            }
            set {
                this.defDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> DefQuantity {
            get {
                return this.defQuantityField;
            }
            set {
                this.defQuantityField = value;
            }
        }
        
        /// <remarks/>
        public long GlobalId {
            get {
                return this.globalIdField;
            }
            set {
                this.globalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> InvDate {
            get {
                return this.invDateField;
            }
            set {
                this.invDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> InvQuantity {
            get {
                return this.invQuantityField;
            }
            set {
                this.invQuantityField = value;
            }
        }
        
        /// <remarks/>
        public string MakeLogo {
            get {
                return this.makeLogoField;
            }
            set {
                this.makeLogoField = value;
            }
        }
        
        /// <remarks/>
        public string MakeName {
            get {
                return this.makeNameField;
            }
            set {
                this.makeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> OrdDate {
            get {
                return this.ordDateField;
            }
            set {
                this.ordDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> OrdQuantity {
            get {
                return this.ordQuantityField;
            }
            set {
                this.ordQuantityField = value;
            }
        }
        
        /// <remarks/>
        public string OptovikLogo {
            get {
                return this.optovikLogoField;
            }
            set {
                this.optovikLogoField = value;
            }
        }
        
        /// <remarks/>
        public long PotrebitelId {
            get {
                return this.potrebitelIdField;
            }
            set {
                this.potrebitelIdField = value;
            }
        }
        
        /// <remarks/>
        public string PotrebitelReference {
            get {
                return this.potrebitelReferenceField;
            }
            set {
                this.potrebitelReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string PriceLogo {
            get {
                return this.priceLogoField;
            }
            set {
                this.priceLogoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> POrdQuantity {
            get {
                return this.pOrdQuantityField;
            }
            set {
                this.pOrdQuantityField = value;
            }
        }
        
        /// <remarks/>
        public string PotrebitelName {
            get {
                return this.potrebitelNameField;
            }
            set {
                this.potrebitelNameField = value;
            }
        }
        
        /// <remarks/>
        public string PotrebitelLogo {
            get {
                return this.potrebitelLogoField;
            }
            set {
                this.potrebitelLogoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PricePotPrevRUR {
            get {
                return this.pricePotPrevRURField;
            }
            set {
                this.pricePotPrevRURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QuestionsCount {
            get {
                return this.questionsCountField;
            }
            set {
                this.questionsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> RecDate {
            get {
                return this.recDateField;
            }
            set {
                this.recDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> RecQuantity {
            get {
                return this.recQuantityField;
            }
            set {
                this.recQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> RecRegDate {
            get {
                return this.recRegDateField;
            }
            set {
                this.recRegDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> RecRegQuantity {
            get {
                return this.recRegQuantityField;
            }
            set {
                this.recRegQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string SubstMakeLogo {
            get {
                return this.substMakeLogoField;
            }
            set {
                this.substMakeLogoField = value;
            }
        }
        
        /// <remarks/>
        public string SubstMakeName {
            get {
                return this.substMakeNameField;
            }
            set {
                this.substMakeNameField = value;
            }
        }
        
        /// <remarks/>
        public string SubstDetailNum {
            get {
                return this.substDetailNumField;
            }
            set {
                this.substDetailNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StoreDatePlan {
            get {
                return this.storeDatePlanField;
            }
            set {
                this.storeDatePlanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StoreDateFact {
            get {
                return this.storeDateFactField;
            }
            set {
                this.storeDateFactField = value;
            }
        }
        
        /// <remarks/>
        public long UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SetInmotionStateBySubIdOutputItem {
        
        private long subIdField;
        
        private int portionField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public long SubId {
            get {
                return this.subIdField;
            }
            set {
                this.subIdField = value;
            }
        }
        
        /// <remarks/>
        public int Portion {
            get {
                return this.portionField;
            }
            set {
                this.portionField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SetInmotionStateBySubIdInputItem {
        
        private long subIdField;
        
        private int portionField;
        
        private SetInmotionStateEnum stateField;
        
        /// <remarks/>
        public long SubId {
            get {
                return this.subIdField;
            }
            set {
                this.subIdField = value;
            }
        }
        
        /// <remarks/>
        public int Portion {
            get {
                return this.portionField;
            }
            set {
                this.portionField = value;
            }
        }
        
        /// <remarks/>
        public SetInmotionStateEnum State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SetInmotionStateEnum {
        
        /// <remarks/>
        Inv,
        
        /// <remarks/>
        Ans,
        
        /// <remarks/>
        Ans0,
        
        /// <remarks/>
        RecReg,
        
        /// <remarks/>
        AccReg,
        
        /// <remarks/>
        Lost,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SetInmotionStateByGlobalIdOutputItem {
        
        private long globalIdField;
        
        private int countField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public long GlobalId {
            get {
                return this.globalIdField;
            }
            set {
                this.globalIdField = value;
            }
        }
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SetInmotionStateByGlobalIdInputItem {
        
        private long globalIdField;
        
        private int countField;
        
        private SetInmotionStateEnum stateField;
        
        /// <remarks/>
        public long GlobalId {
            get {
                return this.globalIdField;
            }
            set {
                this.globalIdField = value;
            }
        }
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public SetInmotionStateEnum State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InmConsumer_v3 : InmConsumer_v2 {
        
        private byte[] timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetWholesalerInmotionCompletedEventHandler(object sender, GetWholesalerInmotionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWholesalerInmotionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWholesalerInmotionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InmWholesaler_v2[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InmWholesaler_v2[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetConsumerInmotionCompletedEventHandler(object sender, GetConsumerInmotionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConsumerInmotionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConsumerInmotionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InmConsumer_v2[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InmConsumer_v2[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetConsumerInmotion3CompletedEventHandler(object sender, GetConsumerInmotion3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConsumerInmotion3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConsumerInmotion3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InmConsumer_v3[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InmConsumer_v3[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void InMotion_SubIdByGlobalIdCompletedEventHandler(object sender, InMotion_SubIdByGlobalIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InMotion_SubIdByGlobalIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InMotion_SubIdByGlobalIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SetInmotionStateByGlobalIdCompletedEventHandler(object sender, SetInmotionStateByGlobalIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetInmotionStateByGlobalIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetInmotionStateByGlobalIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetInmotionStateByGlobalIdOutputItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetInmotionStateByGlobalIdOutputItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SetInmotionStateBySubIdCompletedEventHandler(object sender, SetInmotionStateBySubIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetInmotionStateBySubIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetInmotionStateBySubIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetInmotionStateBySubIdOutputItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetInmotionStateBySubIdOutputItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetWholesalerInmotion_TestCompletedEventHandler(object sender, GetWholesalerInmotion_TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWholesalerInmotion_TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWholesalerInmotion_TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InmWholesaler_v2[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InmWholesaler_v2[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetConsumerInmotion_TestCompletedEventHandler(object sender, GetConsumerInmotion_TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConsumerInmotion_TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConsumerInmotion_TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InmConsumer_v2[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InmConsumer_v2[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetConsumerInmotion3_TestCompletedEventHandler(object sender, GetConsumerInmotion3_TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConsumerInmotion3_TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConsumerInmotion3_TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InmConsumer_v3[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InmConsumer_v3[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TestConnectCompletedEventHandler(object sender, TestConnectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestConnectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestConnectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591